# Generated by Django 4.2.29 on 2026-04-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.resume_directory_path),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruiter_profile_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
