# Generated by Django 4.2.29 on 2026-04-13 04:43

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(null=True, upload_to=profiles.models.resume_directory_path),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(related_name='in_profiles', to='profiles.skill'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
