# Generated by Django 4.2.29 on 2026-04-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='type',
            new_name='work_type',
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('TEN', '10th Pass'), ('TWL', '12th Pass'), ('DIP', 'Diploma'), ('BAC', "Bachelor's Degree"), ('MAS', "Master's Degree"), ('DOC', 'Doctorate'), ('OTH', 'Other')], default='10th Pass', max_length=3),
            preserve_default=False,
        ),
    ]
