# Generated by Django 4.2.29 on 2026-04-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_type_workexperience_work_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_type',
            new_name='workexp_type',
        ),
    ]
