# Generated by Django 4.2.29 on 2026-04-13 13:43

import django.core.validators
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_work_type_workexperience_workexp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(null=True, upload_to=profiles.models.resume_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
