# Generated by Django 4.2.29 on 2026-04-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='workexp_type',
            new_name='work_type',
        ),
    ]
