# Generated by Django 4.2.29 on 2026-04-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_unique_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
