# Generated by Django 4.2.29 on 2026-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
