# Generated by Django 4.2.29 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_description_html'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_job',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='title_type_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'job_type'], name='title_job_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('title', 'job_type', 'created_by'), name='unique_job'),
        ),
    ]
