
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    user: "${UID}:${GID}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A job_board worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: