name: Deploy to Render

on:
  workflow_run:
    workflows: ['Testing']
    types: 
      - completed
      
concurrency:
  group: production
  cancel-in-progress: false
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Webhook Call to Render API
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}
